# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Check slack messages if no reply at 8pm every night JST
on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      CHAT_GPT_API_KEY: ${{ secrets.CHAT_GPT_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Create .env file
        run: |
          envsubst < .github/workflows/.env.template > .env

      - name: Install all dependencies
        run: go mod download

      - name: Build and Run main.go
        run: |
         go run -v ./src/cmd/main.go